# Generated by Django 4.1.7 on 2023-04-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CO', 'Condiments'), ('NT', 'Nuts'), ('BK', 'Bakery'), ('CD', 'Candies'), ('MK', 'Milk'), ('DY', 'Dyes'), ('CH', 'Chemical Products')], max_length=2),
        ),
    ]
