# Generated by Django 4.1.7 on 2023-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='product',
            name='Pgramos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('co', 'Condiments'), ('nt', 'Nuts'), ('bk', 'Bakery'), ('gr', 'Grains'), ('gc', 'Groceries'), ('ch', 'Chemical Products')], max_length=2),
        ),
    ]
