# Generated by Django 4.2.2 on 2025-01-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_cart_product_pgramos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pgramos',
            new_name='ciengramos',
        ),
        migrations.AddField(
            model_name='product',
            name='dccgramos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='mayor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='mediokilo',
            field=models.FloatField(default=0),
        ),
    ]
