# Generated by Django 4.2.2 on 2025-04-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_pgramos_product_ciengramos_product_dccgramos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ciengramos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dccgramos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mayor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mediokilo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('bo', 'Both'), ('un', 'Unit')], default='kg', max_length=2),
        ),
    ]
